- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
- name: CreateUser
  user:
    name: ubuntu
    comment: "Ubuntu"
    group: wheel
    createhome: yes
- name: Set authorized key
  authorized_key:
    user: ubuntu
    shell: /bin/bash
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
- name: Disallow root SSH access
  lineinfile: 
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
- name: Disallow password authentication
  lineinfile: 
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
- name: restart ssh
  service:
    name: ssh
    state: restarted